const PIN_ALIASES = {
  LED_BUILTIN: 13,
  LED_PIN: 13,
  BTN_PIN: 2,
};

function tokenize(source) {
  return String(source || "")
    .replace(/\/\/.*$/gm, "")
    .replace(/\/\*[\s\S]*?\*\//g, "");
}

export function analyzeSketch(source) {
  const text = tokenize(source);
  const aliases = { ...PIN_ALIASES };
  for (const match of text.matchAll(/\b(?:const\s+)?int\s+([A-Za-z_]\w*)\s*=\s*(\d+)\s*;/g)) {
    aliases[match[1]] = Number(match[2]);
  }
  const pins = new Set();
  const writes = [];
  const reads = [];
  const delays = [];
  const re = /(pinMode|digitalWrite|digitalRead|analogRead|analogWrite|delay)\s*\(\s*([^)]+)\)/g;
  let m;
  while ((m = re.exec(text))) {
    const fn = m[1];
    const args = m[2].split(",").map((s) => s.trim());
    if (fn === "delay") delays.push(Number(args[0]) || 0);
    else {
      const raw = args[0];
      const pin = aliases[raw] ?? Number(raw);
      if (Number.isFinite(pin)) pins.add(pin);
      if (fn === "digitalWrite" || fn === "analogWrite") {
        writes.push({ pin, value: args[1] === "HIGH" || Number(args[1]) > 0 });
      }
      if (fn === "digitalRead" || fn === "analogRead") reads.push({ pin, fn });
    }
  }
  return {
    pins: [...pins].sort((a, b) => a - b),
    writes,
    reads,
    delays,
    hasLoop: /void\s+loop\s*\(/.test(text),
    hasSetup: /void\s+setup\s*\(/.test(text),
  };
}

export function runSketch(source, { buttonDown = false, steps = 8 } = {}) {
  const info = analyzeSketch(source);
  const pins = {};
  for (const pin of info.pins) pins[pin] = 0;
  if (buttonDown) pins[2] = 1;
  const frames = [];
  let led = 0;
  const hasToggle = /digitalWrite\s*\(\s*(13|LED_BUILTIN|LED_PIN)/.test(source);
  for (let i = 0; i < steps; i += 1) {
    if (hasToggle) led = i % 2;
    if (buttonDown && /digitalRead/.test(source)) led = 1;
    pins[13] = led;
    frames.push({ t: i, pins: { ...pins }, led: Boolean(led) });
  }
  return {
    ok: info.hasSetup && info.hasLoop,
    info,
    frames,
    abstraction: {
      kind: "firmware-binary",
      entry: "loop",
      io: info.pins,
      note: "Code is one layer; physics is the other. They meet at pins.",
    },
  };
}

export function sketchFromFunctions(functions = []) {
  const labels = functions.map((f) => String(f || "").toLowerCase());
  const hasLed = labels.includes("light") || labels.includes("actuate");
  const hasBtn = labels.includes("sense");
  const ledPin = hasLed || hasBtn;
  const lines = [
    "// Generated by IKEAFY firmware tech — abstraction over the bench.",
    ledPin ? "const int LED_PIN = 13;" : "",
    hasBtn ? "const int BTN_PIN = 2;" : "",
    "",
    "void setup() {",
    ledPin ? "  pinMode(LED_PIN, OUTPUT);" : "  pinMode(LED_BUILTIN, OUTPUT);",
    hasBtn ? "  pinMode(BTN_PIN, INPUT_PULLUP);" : "",
    "}",
    "",
    "void loop() {",
    hasBtn
      ? "  int pressed = digitalRead(BTN_PIN) == LOW;\n  digitalWrite(LED_PIN, pressed ? HIGH : LOW);"
      : "  digitalWrite(LED_BUILTIN, HIGH);\n  delay(200);\n  digitalWrite(LED_BUILTIN, LOW);\n  delay(200);",
    "}",
    "",
  ];
  return lines.filter((l) => l !== undefined).join("\n");
}
